### ISSUE TITLE
getUuid uniemożliwia wywołanie metody put offer-classifieds-packages

### ISSUE THREAD

**Issue by tsubocz** [Wiatrogon/php-allegro-rest-api#18]
Okazuje się, że nie wszystkie metody PUT wymagają podania Uuid - przykładem jest: https://developer.allegro.pl/documentation/#operation/assignClassifiedPackagesUsingPUT

Przez to przy wywołaniu:
`$package_put = $api->sale->commands()->{'offer-classifieds-packages'}($package_data);`
otrzymujemy odpowiedź:
`{"errors":[{"code":"OfferNotFoundException","message":"Offer: b91f6b68-bf54-476f-931a-90e288a4741e not found.","details":null,"path":null,"userMessage":"Offer with id: b91f6b68-bf54-476f-931a-90e288a4741e does not exist."}]}`

Będę wdzięczny za pomoc w rozwiązaniu problemu.

**Comment by retrowaver** [comment]
`UUID` używane jest w przypadku korzystania z `commands`. Tutaj potrzebujesz zrobić zwykłe zapytanie `PUT`:

```php
$package_put = $api->sale->{'offer-classifieds-packages'}(numer_oferty)->put($package_data);

**Comment by tsubocz** [comment]
Hej dzięki za podpowiedź
